services:
  backend:
    image: universityforum-backend-1

    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    network_mode: "host"
    env_file:
      - ./.env
  